# Site settings
title: Amr Eldib
description: Blog and personal website
# >										# this means to ignore newlines until "baseurl:"
baseurl: "/"							# the subpath of your site, e.g. /blog/
url: "http://www.amreldib.com"			# the base hostname & protocol for your site
rss_feed: http://www.amreldib.com/blog/rss.xml
rss_page: http://www.amreldib.com/rss
timezone: Canada/Pacific
categories: [av, blog, bookmarks, bookshelf, favs, linkblog, projects, reviews, talks, tools, writings]

# RSS Titles
rss_title_all: Amr Eldib
rss_title_av: "Amr Eldib's Audio and Video"
rss_title_blog: "Amr Eldib's Blog"
rss_title_bookmarks: "Amr Eldib's Bookmarks"
rss_title_bookshelf: "Amr Eldib's Bookmarks"
rss_title_favs: "Amr Eldib's Favorite Items"
rss_title_linkblog: "Amr Eldib's Linkblog"
rss_title_projects: "Amr Eldib's Projects"
rss_title_reviews: "Amr Eldib's Reviews"
rss_title_talks: "Amr Eldib's Talks"
rss_title_tools: "Amr Eldib's Collection of Tools"
rss_title_writings: "Amr Eldib's Writings"
# RSS descriptions
rss_description_all: "Amr Eldib's Blog and Personal Website"
rss_description_av: "Collection of audio and video recordings I've appeared in"
rss_description_blog: Postings about technology, software development, and GIS
rss_description_bookmarks: Interesting links from around the Internet
rss_description_bookshelf: Browse through my bookself
rss_description_favs: Stuff I like
rss_description_linkblog: Interesting reads and finds everyday
rss_description_projects: "List of projects I've worked on"
rss_description_reviews: Books, Movies, TV Shows, and other random things
rss_description_talks: Talks, sessions and presentations
rss_description_tools: Hardware, Software, and other tools I use every day
rss_description_writings: Random thoughts on random topics

# metadata
author:
  name: 'Amr Eldib'
  nickname: 'Amr'
  url: http://www.amreldib.com
  country: Canada
  image: http://www.amreldib.com/public/images/Amr.png
  image_small: http://www.amreldib.com/public/images/Amr_small.png
  image_avatar: http://www.amreldib.com/public/images/AmrAvatar.png
  username:
    twitter: AmrEldib
    github: AmrEldib
    linkedin: AmrEldib
    goodreads: AmrEldib
    googleplus: AmrEldib

# Custom Properties
imgFolder_root: "/public/images/"
imgFolder_av: "/public/images/av/"
imgFolder_blog: "/public/images/blog/"
imgFolder_bookmarks: "/public/images/bookmarks/"
imgFolder_bookshelf: "/public/images/bookshelf/"
imgFolder_favs: "/public/images/favs/"
imgFolder_projects: "/public/images/projects/"
imgFolder_linkblog: "/public/images/linkblog/"
imgFolder_reviews: "/public/images/reviews/"
imgFolder_tools: "/public/images/tools/"
imgFolder_writings: "/public/images/writings/"

# Permalinks
permalink: "/:categories/:title"
relative_permalinks: false
redirects: yes

# Build settings
#paginate: 5 
markdown: kramdown
highlighter: pygments
encoding: utf-8
exclude: ["amreldib.github.io.sln", "*.suo", "README.md"]
include: ["slides"]

#gems: [jekyll-sitemap]
#gems:
#  - jekyll-redirect-from
