# Site settings
title: Amr Eldib
description: Blog and personal website
# >										# this means to ignore newlines until "baseurl:"
baseurl: "/"							# the subpath of your site, e.g. /blog/
url: "https://amreldib.github.io"			# the base hostname & protocol for your site
timezone: Canada/Pacific
categories: []

# metadata
author:
  name: 'Amr Eldib'
  nickname: 'Amr'
  url: https://amreldib.com
  country: Canada
  image: https://amreldib.github.io/public/images/Amr.png
  image_small: https://amreldib.github.io/public/images/Amr_small.png
  image_avatar: https://amreldib.github.io/public/images/AmrAvatar.png
  username:
    twitter: AmrEldib
    github: AmrEldib
    linkedin: AmrEldib
    goodreads: AmrEldib
    googleplus: AmrEldib

# Custom Properties
imgFolder_root: "/public/images/"

# Permalinks
permalink: "/:categories/:title"
relative_permalinks: false
redirects: yes

# Build settings
#paginate: 5
markdown: kramdown
highlighter: rouge
encoding: utf-8
exclude: ["README.md"]
include: ["slides", "humans.txt", "robots.txt", "keybase.txt"]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# HTML Compression configurations
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

