# Site settings
title: Amr
description: >								# this means to ignore newlines until "baseurl:"
  Blog and personal website
baseurl: "/"								# the subpath of your site, e.g. /blog/
url: "http://amreldib.github.io"			# the base hostname & protocol for your site
rss_feed: http://feeds.feedburner.com/AmrEldib
timezone: Canada/Pacific
categories: [av, blog, bookmarks, bookshelf, favs, projects, reviews, tools, writings]

# Contact Properties
twitter_username: AmrEldib
github_username:  AmrEldib
linkedin_username: AmrEldib
goodreads_username: AmrEldib

# Custom Properties
avImagesFolder: "/public/images/av/"
blogImagesFolder: "/public/images/blog/"
bookmarksImagesFolder: "/public/images/bookmarks/"
bookshelfImagesFolder: "/public/images/bookshelf/"
favsImagesFolder: "/public/images/favs/"
projectsImagesFolder: "/public/images/projects/"
reviewsImagesFolder: "/public/images/reviews/"
toolsImagesFolder: "/public/images/tools/"
writingsImagesFolder: "/public/images/writings/"

# Permalinks
permalink: "/:categories/:title"
relative_permalinks: false
redirects: yes

# metadata
author:
name: 'Amr Eldib'
url: http://www.amreldib.com

# Build settings
#paginate: 5 
markdown: kramdown
highlighter: pygments
encoding: utf-8
exclude: ["amreldib.github.io.sln", "*.suo", "importFromBlogger", "README.md"]
#include: ["TwitterArchive"]
#gems: [jekyll-sitemap]