# Site settings
title: Amr
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog and personal website
baseurl: "/" # the subpath of your site, e.g. /blog/
avImagesFolder: "/public/images/av/"
blogImagesFolder: "/public/images/blog/"
bookmarksImagesFolder: "/public/images/bookmarks/"
favsImagesFolder: "/public/images/favs/"
projectsImagesFolder: "/public/images/projects/"
reviewsImagesFolder: "/public/images/reviews/"
toolsImagesFolder: "/public/images/tools/"
writingsImagesFolder: "/public/images/writings/"
url: "http://amreldib.github.io" # the base hostname & protocol for your site
twitter_username: AmrEldib
github_username:  AmrEldib
linkedin_username: AmrEldib
goodreads_username: AmrEldib
rss_feed: http://feeds.feedburner.com/AmrEldib
timezone: Canada/Pacific
categories: [av, blog, bookmarks, favs, projects, reviews, tools, writings]

# Permalinks
permalink: "/:categories/:title"
relative_permalinks: true
redirects: yes

# metadata
author:
name: 'Amr Eldib'
url: http://www.amreldib.com

# Build settings
#paginate: 5 
markdown: kramdown
highlighter: pygments
encoding: UTF-8
exclude: ["amreldib.github.io.sln", "*.suo", "importFromBlogger", "README.md"]
#include: ["TwitterArchive"]