# Site settings
title: Amr Eldib
description: Blog and personal website
# >										# this means to ignore newlines until "baseurl:"
baseurl: "/"							# the subpath of your site, e.g. /blog/
url: "http://www.amreldib.com"			# the base hostname & protocol for your site
rss_feed: http://www.amreldib.com/blog/rss.xml
rss_page: http://www.amreldib.com/rss
timezone: Canada/Pacific
categories: [av, blog, bookmarks, bookshelf, favs, linkblog, projects, reviews, talks, tools, writings]

# RSS Titles
rss_title_all: Amr Eldib
rss_title_av: "Amr Eldib's Audio and Video"
rss_title_blog: "Amr Eldib's Blog"
rss_title_bookmarks: "Amr Eldib's Bookmarks"
rss_title_bookshelf: "Amr Eldib's Bookmarks"
rss_title_favs: "Amr Eldib's Favorite Items"
rss_title_linkblog: "Amr Eldib's Linkblog"
rss_title_projects: "Amr Eldib's Projects"
rss_title_reviews: "Amr Eldib's Reviews"
rss_title_talks: "Amr Eldib's Talks"
rss_title_tools: "Amr Eldib's Collection of Tools"
rss_title_writings: "Amr Eldib's Writings"
# RSS descriptions
rss_description_all: "Amr Eldib's Blog and Personal Website"
rss_description_av: "Collection of audio and video recordings I've appeared in"
rss_description_blog: Postings about technology, software development, and GIS
rss_description_bookmarks: Interesting links from around the Internet
rss_description_bookshelf: Browse through my bookself
rss_description_favs: Stuff I like
rss_description_linkblog: Interesting reads and finds everyday
rss_description_projects: "List of projects I've worked on"
rss_description_reviews: Books, Movies, TV Shows, and other random things
rss_description_talks: Talks, sessions and presentations
rss_description_tools: Hardware, Software, and other tools I use every day
rss_description_writings: Random thoughts on random topics

# metadata
author:
  name: 'Amr Eldib'
  nickname: 'Amr'
  url: http://www.amreldib.com
  country: Canada
  image: http://www.amreldib.com/public/images/Amr.png
  image_small: http://www.amreldib.com/public/images/Amr_small.png
  image_avatar: http://www.amreldib.com/public/images/AmrAvatar.png
  username:
    twitter: AmrEldib
    github: AmrEldib
    linkedin: AmrEldib
    goodreads: AmrEldib
    googleplus: AmrEldib

# Custom Properties
imgFolder_root: "/public/images/"
imgFolder_av: "/public/images/av/"
imgFolder_blog: "/public/images/blog/"
imgFolder_bookmarks: "/public/images/bookmarks/"
imgFolder_bookshelf: "/public/images/bookshelf/"
imgFolder_favs: "/public/images/favs/"
imgFolder_projects: "/public/images/projects/"
imgFolder_linkblog: "/public/images/linkblog/"
imgFolder_reviews: "/public/images/reviews/"
imgFolder_tools: "/public/images/tools/"
imgFolder_writings: "/public/images/writings/"
audioFolder_root: "/public/audio/"

# Permalinks
permalink: "/:categories/:title"
relative_permalinks: false
redirects: yes

# Build settings
#paginate: 5 
markdown: kramdown
highlighter: pygments
encoding: utf-8
exclude: ["amreldib.github.io.sln", "*.suo", "README.md"]
include: ["slides", "humans.txt", "robots.txt", "keybase.txt"]

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# prose.io configurations
prose:
  rooturl: ''
  siteurl: 'http://www.amreldib.com/'
  relativeLinks: 'http://www.amreldib.com/proseRelativeLinks.jsonp'
  media: 'public/images'
  ignore:
    - .gitattributes
    - .gitignore
    - README.md
    - _config.yml
    - /_layouts
    - /_includes
    - /_plugins
    - /_site
    - public
    - resume
    - slides
    - CNAME
    - WebEssentials2015-Settings.json
    - amreldib.github.io.sln
    - bundleconfig.json
    - keybase.txt
    - humans.txt
    - robots.txt
    - vwd.webinfo
    - 404.html
  metadata:
    av/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "avPost"
      - name: "category"
        field:
          element: "hidden"
          value: "av"
      - name: "name"
        field:
          element: "text"
          label: "Name"
          placeholder: "UniqueName"
          type: "text"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Post title"
          type: "text"
      - name: "time"
        field:
          element: "text"
          label: "Timestamp"
          value: "2015-02-20 22:21:00 -08:00"
          type: "text"
          help: "Add time in this format: 2015-02-20 22:21:00 -08:00"
      - name: "commentsSection"
        field:
          element: "checkbox"
          label: "Comments Section"
          value: "false"
          help: "Add a comments section at the end of the post?"
      - name: "frontpage"
        field:
          element: "checkbox"
          label: "Show post on front page"
          value: "true"
          help: "Show the full text of this post on the front page?"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Source Control"
              value: "Source Control"
            - name: "Javascript"
              value: "Javascript"
            - name: "Microsoft"
              value: "Microsoft"
    blog/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "blogPost"
      - name: "category"
        field:
          element: "hidden"
          value: "blog"
      - name: "name"
        field:
          element: "text"
          label: "Name"
          placeholder: "UniqueName"
          type: "text"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Post title"
          type: "text"
      - name: "time"
        field:
          element: "text"
          label: "Timestamp"
          value: "2015-02-20 22:21:00 -08:00"
          type: "text"
          help: "Add time in this format: 2015-02-20 22:21:00 -08:00"
      - name: "commentsSection"
        field:
          element: "checkbox"
          label: "Comments Section"
          value: "true"
          help: "Add a comments section at the end of the post?"
      - name: "frontpage"
        field:
          element: "checkbox"
          label: "Show post on front page"
          value: "true"
          help: "Show the full text of this post on the front page?"
      - name: "redirects"
        field:
          element: "text"
          label: "URL to redirect from"
          placeholder: "/some/url/of/page.html"
          type: "text"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Talk"
              value: "Talk"
            - name: "GitHub"
              value: "GitHub"
            - name: "Maptime"
              value: "Maptime"
            - name: "Firefox"
              value: "Firefox"
            - name: "IT Industry"
              value: "IT Industry"
            - name: "Windows"
              value: "Windows"
            - name: "Microsoft"
              value: "Microsoft"
            - name: "Tools"
              value: "Tools"
            - name: "Google"
              value: "Google"
            - name: "GIS"
              value: "GIS"
            - name: "Apple"
              value: "Apple"
            - name: "Software Development"
              value: "Software Development"
            - name: "Wish List"
              value: "Wish List"
            - name: "Mozilla"
              value: "Mozilla"
            - name: ".NET"
              value: ".NET"
            - name: "C#"
              value: "C#"
            - name: "Visual Studio"
              value: "Visual Studio"
            - name: "VMware"
              value: "VMware"
            - name: "Virtualization"
              value: "Virtualization"
            - name: "VirtualBox"
              value: "VirtualBox"
            - name: "iPhone"
              value: "iPhone"
            - name: "Chrome"
              value: "Chrome"
            - name: "App Store"
              value: "App Store"
            - name: "Android"
              value: "Android"
            - name: "Mozilla Nightly"
              value: "Mozilla Nightly"
            - name: "Ubuntu"
              value: "Ubuntu"
            - name: "Linux"
              value: "Linux"
            - name: "PowerShell"
              value: "PowerShell"
            - name: "Adobe"
              value: "Adobe"
            - name: "Podcast"
              value: "Podcast"
            - name: "EgyGeeks"
              value: "EgyGeeks"
            - name: "Community"
              value: "Community"
            - name: "Egypt"
              value: "Egypt"
            - name: "Cloud"
              value: "Cloud"
            - name: "Open Source"
              value: "Open Source"
            - name: "Esri"
              value: "Esri"
            - name: "ArcGIS"
              value: "ArcGIS"
            - name: "Javascript"
              value: "Javascript"
            - name: "SignalR"
              value: "SignalR"
            - name: "Code"
              value: "Code"
            - name: "Tips"
              value: "Tips"
            - name: "HTML"
              value: "HTML"
            - name: "CSS"
              value: "CSS"
            - name: "Arabic"
              value: "Arabic"
            - name: "Office"
              value: "Office"
            - name: "Outlook"
              value: "Outlook"
            - name: "Chocolatey"
              value: "Chocolatey"
            - name: "DevTools"
              value: "DevTools"
    linkblog/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "linkPost"
      - name: "category"
        field:
          element: "hidden"
          value: "linkblog"
      - name: "name"
        field:
          element: "text"
          label: "Name"
          placeholder: "UniqueName"
          type: "text"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Post title"
          type: "text"
      - name: "time"
        field:
          element: "text"
          label: "Timestamp"
          value: "2015-02-20 22:21:00 -08:00"
          type: "text"
          help: "Add time in this format: 2015-02-20 22:21:00 -08:00"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "video"
              value: "video"
            - name: "robots"
              value: "robots"
            - name: "top gear"
              value: "top gear"
            - name: "personal cloud"
              value: "personal cloud"
            - name: "web"
              value: "web"
            - name: "mozilla"
              value: "mozilla"
            - name: "firefox"
              value: "firefox"
            - name: "gis"
              value: "gis"
    projects/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "projectsPost"
      - name: "category"
        field:
          element: "hidden"
          value: "projects"
      - name: "name"
        field:
          element: "text"
          label: "Name"
          placeholder: "UniqueName"
          type: "text"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Post title"
          type: "text"
      - name: "time"
        field:
          element: "text"
          label: "Timestamp"
          value: "2015-02-20 22:21:00 -08:00"
          type: "text"
          help: "Add time in this format: 2015-02-20 22:21:00 -08:00"
      - name: "frontpage"
        field:
          element: "checkbox"
          label: "Show post on front page"
          value: "true"
          help: "Show the full text of this post on the front page?"
    reviews/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "reviewsPost"
      - name: "category"
        field:
          element: "hidden"
          value: "reviews"
      - name: "name"
        field:
          element: "text"
          label: "Name"
          placeholder: "UniqueName"
          type: "text"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Post title"
          type: "text"
      - name: "excerpt"
        field:
          element: "text"
          label: "Excerpt"
          placeholder: "Short excerpt from the post, or short summary"
          type: "text"
      - name: "time"
        field:
          element: "text"
          label: "Timestamp"
          value: "2015-02-20 22:21:00 -08:00"
          type: "text"
          help: "Add time in this format: 2015-02-20 22:21:00 -08:00"
      - name: "rating"
        field:
          element: "number"
          label: "Rating"
          value: "3"
          type: "number"
          help: "Choose a rating between 0 and 5"
      - name: "frontpage"
        field:
          element: "checkbox"
          label: "Show post on front page"
          value: "true"
          help: "Show the full text of this post on the front page?"
      - name: "lang"
        field:
          element: "select"
          label: "Language"
          value: "en"
          options:
            - name: "Arabic"
              value: "ar"
            - name: "English"
              value: "en"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "History"
              value: "History"
            - name: "Politics"
              value: "Politics"
            - name: "Religion"
              value: "Religion"
            - name: "Book Review"
              value: "Book Review"
            - name: "Internet"
              value: "Internet"
            - name: "Economics"
              value: "Economics"
            - name: "Tech"
              value: "Tech"
            - name: "Business"
              value: "Business"
            - name: "Software"
              value: "Software"
            - name: "Work"
              value: "Work"
            - name: "Biography"
              value: "Biography"
            - name: "Apple"
              value: "Apple"
            - name: "Google"
              value: "Google"
            - name: "Non-fiction"
              value: "Non-fiction"
    writings/_posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "writingsPost"
      - name: "category"
        field:
          element: "hidden"
          value: "writings"
      - name: "name"
        field:
          element: "text"
          label: "Name"
          placeholder: "UniqueName"
          type: "text"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Post title"
          type: "text"
      - name: "time"
        field:
          element: "text"
          label: "Timestamp"
          value: "2015-02-20 22:21:00 -08:00"
          type: "text"
          help: "Add time in this format: 2015-02-20 22:21:00 -08:00"
      - name: "commentsSection"
        field:
          element: "checkbox"
          label: "Comments Section"
          value: "false"
          help: "Add a comments section at the end of the post?"
      - name: "frontpage"
        field:
          element: "checkbox"
          label: "Show post on front page"
          value: "true"
          help: "Show the full text of this post on the front page?"
      - name: "imageGallery"
        field:
          element: "checkbox"
          label: "Image Gallery"
          value: "true"
          help: "Post contains image gallery?"
      - name: "redirects"
        field:
          element: "text"
          label: "URL to redirect from"
          placeholder: "/some/url/of/page.html"
          type: "text"
      - name: "lang"
        field:
          element: "select"
          label: "Language"
          value: "en"
          options:
            - name: "Arabic"
              value: "ar"
            - name: "English"
              value: "en"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "ASOIAF"
              value: "ASOIAF"
